name: besslogic
services:
  web:
    image: nginx
    networks:
      - backend
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./web/default.conf:/etc/nginx/templates/default.conf.template
    depends_on:
      - frontend
      - backend
    secrets:
      - certs.pub
      - certs.key
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - local.db.env
    networks:
      - backend
  frontend:
    image: node:19
    user: node
    env_file:
      - local.frontend.env
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: ['npm', 'run', 'start']
    tty: true
    stdin_open: true
    expose:
      - '4200'
    networks:
      - backend
  backend:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ['dotnet', 'watch', 'run']
    tty: true
    stdin_open: true
    expose:
      - '5223'
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:

secrets:
  certs.pub:
    file: ./web/besslogic.local.pem
  certs.key:
    file: ./web/besslogic.local-key.pem